services:
  portal-gdn:
    # build: .
    image: ghcr.io/gerbang-digital-nusantara/portal-gdn:latest
    container_name: portal-gdn-container
    ports:
      - "3081:4000"

    env_file:
      - server/.env

    restart: unless-stopped

    networks:
      - backend
      - frontend

networks:
  backend:
    external: true
  frontend:
    external: true
