// Data seed Portal GDN — disalin apa adanya dari mock data di src/App.jsx (§3).
// Dipakai oleh db/seed.js untuk mengisi database awal (demo).
//
// Password tiap user mengikuti pola: `<id>123`  (mis. budhi -> "budhi123").

export const USERS = [
  { id: "budhi",    name: "Budhi",    email: "budhi@email.com",    role: "owner",   unitId: null,          subUnitId: null },
  { id: "rarra",    name: "Rarra",    email: "rarra@email.com",    role: "owner",   unitId: null,          subUnitId: null },
  { id: "lovia",    name: "Lovia",    email: "lovia@email.com",    role: "finance", unitId: null,          subUnitId: null },
  { id: "didi",     name: "Didi",     email: "didi@email.com",     role: "hr",      unitId: null,          subUnitId: null },
  { id: "satya",    name: "Satya",    email: "satya@email.com",    role: "leader",  unitId: "aquaculture", subUnitId: null },
  { id: "taufik",   name: "Taufik",   email: "taufik@email.com",   role: "leader",  unitId: "tanjung",     subUnitId: null },
  { id: "fahrizal", name: "Fahrizal", email: "fahrizal@email.com", role: "leader",  unitId: "xpanca",      subUnitId: null },
  { id: "sugianto", name: "Sugianto", email: "sugianto@email.com", role: "leader",  unitId: "pixel",       subUnitId: null },
  { id: "ferry",    name: "Ferry",    email: "ferry@email.com",    role: "leader",  unitId: "retail",      subUnitId: null },
  { id: "rafli",    name: "Rafli",    email: "rafli@email.com",    role: "pic",     unitId: "aquaculture", subUnitId: "aqua-cerelek" },
  { id: "wahyu",    name: "Wahyu",    email: "wahyu@email.com",    role: "pic",     unitId: "aquaculture", subUnitId: "aqua-cisampih" },
  { id: "hendra",   name: "Hendra",   email: "hendra@email.com",   role: "pic",     unitId: "tanjung",     subUnitId: "tjg-blok-a" },
  { id: "andi",     name: "Andi",     email: "andi@email.com",     role: "pic",     unitId: "pixel",       subUnitId: "pix-bdg-pusat" },
  { id: "rina",     name: "Rina",     email: "rina@email.com",     role: "pic",     unitId: "pixel",       subUnitId: "pix-bdg-timur" },
  { id: "bayu",     name: "Bayu",     email: "bayu@email.com",     role: "pic",     unitId: "retail",      subUnitId: "rtl-outlet1" },
];

export const UNITS = [
  { id: "pixel",       name: "Pixel Telemedia", leaderId: "sugianto", color: "#3B7BC4", colorDark: "#2C5F9E", colorLight: "#E7F0F8", icon: "signal" },
  { id: "retail",      name: "KK / Retail",     leaderId: "ferry",    color: "#C9A45C", colorDark: "#9A7B3E", colorLight: "#F4ECDB", icon: "store" },
  { id: "aquaculture", name: "Aquaculture",     leaderId: "satya",    color: "#5B9B47", colorDark: "#3F6E31", colorLight: "#EAF3E5", icon: "fish" },
  { id: "tanjung",     name: "Kolam Tanjung",   leaderId: "taufik",   color: "#3B9BA4", colorDark: "#2A6E75", colorLight: "#E4F2F3", icon: "water" },
  { id: "xpanca",      name: "Xpanca",          leaderId: "fahrizal", color: "#7A6CB0", colorDark: "#564B80", colorLight: "#ECE9F4", icon: "cog" },
  { id: "menjala",     name: "Menjala",         leaderId: null,       color: "#6B6B76", colorDark: "#46464E", colorLight: "#F0F0F2", icon: "fish" },
];

export const SUB_UNITS = [
  { id: "aqua-cerelek",  unitId: "aquaculture", name: "Kolam Cerelek",        picId: "rafli",  icon: "fish",   status: "active", createdAt: "2025-08-15" },
  { id: "aqua-cisampih", unitId: "aquaculture", name: "Kolam Cisampih",       picId: "wahyu",  icon: "water",  status: "active", createdAt: "2025-08-15" },
  { id: "aqua-ciwastra", unitId: "aquaculture", name: "Kolam Ciwastra",       picId: null,     icon: "fish",   status: "active", createdAt: "2026-01-10" },
  { id: "tjg-blok-a",    unitId: "tanjung",     name: "Tanjung Blok A",       picId: "hendra", icon: "water",  status: "active", createdAt: "2025-09-01" },
  { id: "tjg-blok-b",    unitId: "tanjung",     name: "Tanjung Blok B",       picId: null,     icon: "water",  status: "active", createdAt: "2025-09-01" },
  { id: "pix-bdg-pusat", unitId: "pixel",       name: "Cabang Bandung Pusat", picId: "andi",   icon: "signal", status: "active", createdAt: "2024-03-01" },
  { id: "pix-bdg-timur", unitId: "pixel",       name: "Cabang Bandung Timur", picId: "rina",   icon: "signal", status: "active", createdAt: "2026-03-15" },
  { id: "rtl-outlet1",   unitId: "retail",      name: "Outlet Dago",          picId: "bayu",   icon: "store",  status: "active", createdAt: "2025-06-01" },
  { id: "rtl-outlet2",   unitId: "retail",      name: "Outlet Setiabudi",     picId: null,     icon: "store",  status: "active", createdAt: "2025-11-01" },
  { id: "xpc-main",      unitId: "xpanca",      name: "Xpanca Utama",         picId: null,     icon: "cog",    status: "active", createdAt: "2024-01-01" },
];

export const PROJECTS = [
  { id: "pj-001", unitId: "aquaculture", subUnitId: "aqua-cerelek",  name: "Pembukaan Kolam Cerelek 2",        desc: "Ekspansi 8 kolam baru kapasitas 5 ton/siklus",  status: "on_track", milestonesTotal: 7, milestonesDone: 3, budgetPlanned: 180000000, budgetSpent:  67000000, startDate: "2026-01-15", endDate: "2026-12-31" },
  { id: "pj-002", unitId: "aquaculture", subUnitId: null,            name: "Implementasi Sistem Biofloc",      desc: "Migrasi semua kolam ke biofloc system",         status: "at_risk",  milestonesTotal: 5, milestonesDone: 1, budgetPlanned:  45000000, budgetSpent:  18000000, startDate: "2026-03-01", endDate: "2026-09-30" },
  { id: "pj-101", unitId: "tanjung",     subUnitId: "tjg-blok-a",    name: "Instalasi Filter Multi-tahap",     desc: "Sistem filter 10x2m zigzag + UV sterilization", status: "on_track", milestonesTotal: 8, milestonesDone: 5, budgetPlanned:  43000000, budgetSpent:  26000000, startDate: "2026-04-01", endDate: "2026-07-31" },
  { id: "pj-201", unitId: "pixel",       subUnitId: "pix-bdg-timur", name: "Setup Cabang Bandung Timur",       desc: "Buka cabang baru target 5rb trx/bulan",         status: "on_track", milestonesTotal: 6, milestonesDone: 4, budgetPlanned:  45000000, budgetSpent:  22000000, startDate: "2026-03-01", endDate: "2026-09-30" },
  { id: "pj-202", unitId: "pixel",       subUnitId: null,            name: "Upgrade Sistem POS",               desc: "Ganti sistem kasir ke POS terintegrasi",        status: "behind",   milestonesTotal: 5, milestonesDone: 1, budgetPlanned:  28000000, budgetSpent:  19000000, startDate: "2026-02-01", endDate: "2026-06-30" },
  { id: "pj-301", unitId: "retail",      subUnitId: null,            name: "Rebranding Gera Creative",         desc: "Redesign identitas brand & website",            status: "behind",   milestonesTotal: 5, milestonesDone: 2, budgetPlanned:  35000000, budgetSpent:  28000000, startDate: "2026-01-15", endDate: "2026-06-30" },
  { id: "pj-302", unitId: "retail",      subUnitId: "rtl-outlet2",   name: "Renovasi Outlet Setiabudi",        desc: "Renovasi interior & signage outlet baru",       status: "on_track", milestonesTotal: 6, milestonesDone: 5, budgetPlanned:  52000000, budgetSpent:  45000000, startDate: "2026-02-01", endDate: "2026-06-15" },
  { id: "pj-401", unitId: "xpanca",      subUnitId: null,            name: "Pengembangan Software Distribusi", desc: "Sistem digital order, stok, laporan",           status: "at_risk",  milestonesTotal: 7, milestonesDone: 2, budgetPlanned:  85000000, budgetSpent:  18000000, startDate: "2026-02-01", endDate: "2026-08-31" },
];

export const FORM_TEMPLATES = [
  {
    id: "tpl-kolam-deder", name: "Kolam Deder",
    description: "Template KPI untuk siklus pendederan ikan (larva → benih)",
    frequency: "cycle", createdAt: "2026-01-10",
    fields: [
      { id: "f1",  name: "Tanggal_Tebar",             type: "date",   satuan: "",      source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f2",  name: "Tanggal_Panen",             type: "date",   satuan: "",      source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f3",  name: "Tebar",                     type: "number", satuan: "ekor",  source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f4",  name: "SR",                        type: "number", satuan: "%",     source: "Manual",   formulaId: null,                   defaultWeight: 25, isMargin: false },
      { id: "f5",  name: "Bobot_per_Ekor",            type: "number", satuan: "gr",    source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f6",  name: "FCR",                       type: "number", satuan: "x",     source: "Manual",   formulaId: null,                   defaultWeight: 25, isMargin: false },
      { id: "f7",  name: "Harga_Jual",                type: "number", satuan: "Rp",    source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f8",  name: "Harga_Benih_per_ekor",      type: "number", satuan: "Rp",    source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f9",  name: "Harga_Pakan",               type: "number", satuan: "Rp/kg", source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f10", name: "Biaya_Borongan_Panen",      type: "number", satuan: "Rp",    source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f11", name: "Biaya_per_kg_Panen",        type: "number", satuan: "Rp/kg", source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f12", name: "Biaya_Pemeliharaan_per_kg", type: "number", satuan: "Rp/kg", source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f13", name: "Biaya_CapEx",               type: "number", satuan: "Rp",    source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f14", name: "Biaya_Lain-lain",           type: "number", satuan: "Rp",    source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f15", name: "Panen",                     type: "auto",   satuan: "ekor",  source: "Formula",  formulaId: "panen_dari_sr",        defaultWeight: 0,  isMargin: false },
      { id: "f16", name: "Berat_Panen",               type: "auto",   satuan: "kg",    source: "Formula",  formulaId: "berat_dari_bobot",     defaultWeight: 0,  isMargin: false },
      { id: "f17", name: "Pakan",                     type: "auto",   satuan: "kg",    source: "Formula",  formulaId: "pakan_dari_fcr",       defaultWeight: 0,  isMargin: false },
      { id: "f18", name: "HPP_Benih",                 type: "auto",   satuan: "Rp",    source: "Formula",  formulaId: "hpp_benih_ekor",       defaultWeight: 0,  isMargin: false },
      { id: "f19", name: "HPP_Pakan",                 type: "auto",   satuan: "Rp",    source: "Formula",  formulaId: "hpp_pakan",            defaultWeight: 0,  isMargin: false },
      { id: "f20", name: "Total_Biaya",               type: "auto",   satuan: "Rp",    source: "Formula",  formulaId: "total_biaya_komponen", defaultWeight: 0,  isMargin: false },
      { id: "f21", name: "HPP",                       type: "auto",   satuan: "Rp/kg", source: "Formula",  formulaId: "hpp_dari_total",       defaultWeight: 25, isMargin: false },
      { id: "f22", name: "Omset",                     type: "auto",   satuan: "Rp",    source: "Formula",  formulaId: "omset",                defaultWeight: 0,  isMargin: false },
      { id: "f23", name: "Margin",                    type: "auto",   satuan: "Rp",    source: "Formula",  formulaId: "margin_dari_total",    defaultWeight: 25, isMargin: true  },
    ],
  },
  {
    id: "tpl-kolam-pembesaran", name: "Kolam Pembesaran",
    description: "Template KPI untuk siklus pembesaran ikan konsumsi",
    frequency: "cycle", createdAt: "2026-01-10",
    fields: [
      { id: "f1",  name: "Tanggal_Tebar",             type: "date",   satuan: "",      source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f2",  name: "Tanggal_Panen",             type: "date",   satuan: "",      source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f3",  name: "Kg_Tebar",                  type: "number", satuan: "kg",    source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f4",  name: "Ukuran_Tebar",              type: "number", satuan: "gr",    source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f5",  name: "SR",                        type: "number", satuan: "%",     source: "Manual",   formulaId: null,                   defaultWeight: 25, isMargin: false },
      { id: "f6",  name: "Bobot_per_Ekor",            type: "number", satuan: "gr",    source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f7",  name: "FCR",                       type: "number", satuan: "x",     source: "Manual",   formulaId: null,                   defaultWeight: 25, isMargin: false },
      { id: "f8",  name: "Harga_Jual",                type: "number", satuan: "Rp",    source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f9",  name: "Harga_Benih_per_kg",        type: "number", satuan: "Rp/kg", source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f10", name: "Harga_Pakan",               type: "number", satuan: "Rp/kg", source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f11", name: "Biaya_Borongan_Panen",      type: "number", satuan: "Rp",    source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f12", name: "Biaya_per_kg_Panen",        type: "number", satuan: "Rp/kg", source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f13", name: "Biaya_Pemeliharaan_per_kg", type: "number", satuan: "Rp/kg", source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f14", name: "Biaya_CapEx",               type: "number", satuan: "Rp",    source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f15", name: "Biaya_Lain-lain",           type: "number", satuan: "Rp",    source: "Manual",   formulaId: null,                   defaultWeight: 0,  isMargin: false },
      { id: "f16", name: "Tebar",                     type: "auto",   satuan: "ekor",  source: "Formula",  formulaId: "populasi_dari_kg",     defaultWeight: 0,  isMargin: false },
      { id: "f17", name: "Panen",                     type: "auto",   satuan: "ekor",  source: "Formula",  formulaId: "panen_dari_sr",        defaultWeight: 0,  isMargin: false },
      { id: "f18", name: "Berat_Panen",               type: "auto",   satuan: "kg",    source: "Formula",  formulaId: "berat_dari_bobot",     defaultWeight: 0,  isMargin: false },
      { id: "f19", name: "Pakan",                     type: "auto",   satuan: "kg",    source: "Formula",  formulaId: "pakan_dari_fcr",       defaultWeight: 0,  isMargin: false },
      { id: "f20", name: "HPP_Benih",                 type: "auto",   satuan: "Rp",    source: "Formula",  formulaId: "hpp_benih_kg",         defaultWeight: 0,  isMargin: false },
      { id: "f21", name: "HPP_Pakan",                 type: "auto",   satuan: "Rp",    source: "Formula",  formulaId: "hpp_pakan",            defaultWeight: 0,  isMargin: false },
      { id: "f22", name: "Total_Biaya",               type: "auto",   satuan: "Rp",    source: "Formula",  formulaId: "total_biaya_komponen", defaultWeight: 0,  isMargin: false },
      { id: "f23", name: "HPP",                       type: "auto",   satuan: "Rp/kg", source: "Formula",  formulaId: "hpp_dari_total",       defaultWeight: 25, isMargin: false },
      { id: "f24", name: "Omset",                     type: "auto",   satuan: "Rp",    source: "Formula",  formulaId: "omset",                defaultWeight: 0,  isMargin: false },
      { id: "f25", name: "Margin",                    type: "auto",   satuan: "Rp",    source: "Formula",  formulaId: "margin_dari_total",    defaultWeight: 25, isMargin: true  },
    ],
  },
  {
    id: "tpl-cabang-pulsa", name: "Cabang Pulsa Bulanan",
    description: "Template KPI bulanan untuk cabang distribusi pulsa",
    frequency: "monthly", createdAt: "2026-01-15",
    fields: [
      { id: "f1", name: "Jumlah_Transaksi", type: "number", satuan: "trx",   source: "Manual",    formulaId: null,            defaultWeight: 25, isMargin: false },
      { id: "f2", name: "Omset",            type: "number", satuan: "Rp",    source: "Pembukuan", formulaId: null,            defaultWeight: 25, isMargin: false },
      { id: "f3", name: "Total_Biaya",      type: "number", satuan: "Rp",    source: "Pembukuan", formulaId: null,            defaultWeight: 0,  isMargin: false },
      { id: "f4", name: "Total_Agen",       type: "number", satuan: "orang", source: "Manual",    formulaId: null,            defaultWeight: 0,  isMargin: false },
      { id: "f5", name: "Agen_Aktif",       type: "number", satuan: "orang", source: "Manual",    formulaId: null,            defaultWeight: 0,  isMargin: false },
      { id: "f6", name: "Aktivasi_Agen",    type: "auto",   satuan: "%",     source: "Formula",   formulaId: "aktivasi_agen", defaultWeight: 20, isMargin: false },
      { id: "f7", name: "Rata²_per_Trx",    type: "auto",   satuan: "Rp",    source: "Formula",   formulaId: "avg_per_trx",   defaultWeight: 10, isMargin: false },
      { id: "f8", name: "Margin",           type: "auto",   satuan: "Rp",    source: "Formula",   formulaId: "margin",        defaultWeight: 20, isMargin: true  },
    ],
  },
  {
    id: "tpl-outlet-retail", name: "Outlet Retail Bulanan",
    description: "Template KPI bulanan untuk outlet retail",
    frequency: "monthly", createdAt: "2026-02-01",
    fields: [
      { id: "f1", name: "Omset",            type: "number", satuan: "Rp",    source: "Pembukuan", formulaId: null,        defaultWeight: 30, isMargin: false },
      { id: "f2", name: "Total_Biaya",      type: "number", satuan: "Rp",    source: "Pembukuan", formulaId: null,        defaultWeight: 0,  isMargin: false },
      { id: "f3", name: "Jumlah_Pelanggan", type: "number", satuan: "orang", source: "Manual",    formulaId: null,        defaultWeight: 20, isMargin: false },
      { id: "f4", name: "Stock_Loss",       type: "number", satuan: "Rp",    source: "Manual",    formulaId: null,        defaultWeight: 20, isMargin: false },
      { id: "f5", name: "Margin",           type: "auto",   satuan: "Rp",    source: "Formula",   formulaId: "margin",    defaultWeight: 30, isMargin: true  },
    ],
  },
];

export const KPI_SUBMISSIONS = [
  { id: "sub-001", templateId: "tpl-kolam-deder", subUnitId: "aqua-cerelek", unitId: "aquaculture", status: "closed", period: "Siklus Feb-Mei 2026",
    estimatedValues: { f3: 12000, f4: 85, f5: 250, f6: 1.2, f7: 22000, f8: 150, f9: 12000, f10: 1500000, f11: 1200, f12: 8000, f13: 3000000, f14: 1000000 },
    actualValues:    { f3: 12000, f4: 85, f5: 250, f6: 1.24, f7: 22000, f8: 150, f9: 12500, f10: 1800000, f11: 1300, f12: 8500, f13: 3000000, f14: 1200000 },
    fieldWeights: { f4: 25, f6: 25, f21: 25, f23: 25 }, subUnitWeight: 40,
    createdBy: "rafli", createdAt: "2026-02-10", approvedBy: "budhi", approvedAt: "2026-02-12", closedAt: "2026-05-28",
    closingNote: "Panen dilakukan H+105. SR sedikit di bawah target karena suhu malam turun di minggu ke-8." },
  { id: "sub-002", templateId: "tpl-kolam-deder", subUnitId: "aqua-cerelek", unitId: "aquaculture", status: "approved", period: "Siklus Mei-Agu 2026",
    estimatedValues: { f3: 13000, f4: 87, f5: 260, f6: 1.18, f7: 23000, f8: 155, f9: 12500, f10: 1600000, f11: 1250, f12: 8200, f13: 3000000, f14: 1100000 },
    actualValues: null, fieldWeights: { f4: 25, f6: 25, f21: 25, f23: 25 }, subUnitWeight: 40,
    createdBy: "rafli", createdAt: "2026-05-15", approvedBy: "budhi", approvedAt: "2026-05-17", closedAt: null, closingNote: null },
  { id: "sub-003", templateId: "tpl-kolam-deder", subUnitId: "aqua-cisampih", unitId: "aquaculture", status: "estimated", period: "Siklus Mei-Agu 2026",
    estimatedValues: { f3: 11000, f4: 84, f5: 240, f6: 1.25, f7: 22000, f8: 150, f9: 12000, f10: 1400000, f11: 1200, f12: 7800, f13: 2800000, f14: 900000 },
    actualValues: null, fieldWeights: {}, subUnitWeight: 35,
    createdBy: "wahyu", createdAt: "2026-05-20", approvedBy: null, approvedAt: null, closedAt: null, closingNote: null },
  { id: "sub-004", templateId: "tpl-cabang-pulsa", subUnitId: "pix-bdg-pusat", unitId: "pixel", status: "approved", period: "Mei 2026",
    estimatedValues: { f1: 9500, f2: 380000000, f3: 32000000, f4: 150, f5: 130 },
    actualValues:    { f1: 9800, f2: 412000000, f3: 35000000, f4: 152, f5: 138 },
    fieldWeights: { f1: 25, f2: 25, f6: 20, f7: 10, f8: 20 }, subUnitWeight: 70,
    createdBy: "andi", createdAt: "2026-05-01", approvedBy: "budhi", approvedAt: "2026-05-02", closedAt: null, closingNote: null },
  { id: "sub-005", templateId: "tpl-cabang-pulsa", subUnitId: "pix-bdg-timur", unitId: "pixel", status: "closed", period: "Mei 2026",
    estimatedValues: { f1: 5000, f2: 150000000, f3: 12000000, f4: 80, f5: 65 },
    actualValues:    { f1: 4200, f2: 96000000, f3: 10000000, f4: 78, f5: 48 },
    fieldWeights: { f1: 25, f2: 25, f6: 20, f7: 10, f8: 20 }, subUnitWeight: 30,
    createdBy: "rina", createdAt: "2026-05-01", approvedBy: "budhi", approvedAt: "2026-05-03", closedAt: "2026-05-31",
    closingNote: "Cabang baru (buka Mar 2026), masih tahap pengembangan jaringan agen. Margin 96jt dari target 150jt — agen aktif baru 48 dari 78 terdaftar. Fokus Juni: aktivasi agen tidur." },
  { id: "sub-006", templateId: "tpl-cabang-pulsa", subUnitId: "tjg-blok-a", unitId: "tanjung", status: "closed", period: "Mei 2026",
    estimatedValues: { f1: 6000, f2: 40000000, f3: 2500000, f4: 60, f5: 50 },
    actualValues:    { f1: 6300, f2: 37500000, f3: 2300000, f4: 62, f5: 54 },
    fieldWeights: { f1: 25, f2: 25, f6: 20, f7: 10, f8: 20 }, subUnitWeight: 60,
    createdBy: "hendra", createdAt: "2026-05-01", approvedBy: "budhi", approvedAt: "2026-05-02", closedAt: "2026-05-31",
    closingNote: "Produksi stabil, margin 37.5jt mendekati target 40jt. Performa baik." },
  { id: "sub-007", templateId: "tpl-cabang-pulsa", subUnitId: "tjg-blok-b", unitId: "tanjung", status: "closed", period: "Mei 2026",
    estimatedValues: { f1: 4500, f2: 30000000, f3: 2000000, f4: 45, f5: 38 },
    actualValues:    { f1: 4000, f2: 21000000, f3: 1900000, f4: 44, f5: 30 },
    fieldWeights: { f1: 25, f2: 25, f6: 20, f7: 10, f8: 20 }, subUnitWeight: 40,
    createdBy: "taufik", createdAt: "2026-05-01", approvedBy: "budhi", approvedAt: "2026-05-03", closedAt: "2026-05-31",
    closingNote: "Margin 21jt di bawah target 30jt. Blok B belum punya PIC tetap — input oleh Leader. Perlu penugasan PIC." },
  { id: "sub-008", templateId: "tpl-outlet-retail", subUnitId: "rtl-outlet1", unitId: "retail", status: "closed", period: "Mei 2026",
    estimatedValues: { f1: 85000000, f2: 0, f3: 1200, f4: 1500000 },
    actualValues:    { f1: 72000000, f2: 0, f3: 1150, f4: 1800000 },
    fieldWeights: { f1: 30, f3: 20, f4: 20, f5: 30 }, subUnitWeight: 60,
    createdBy: "bayu", createdAt: "2026-05-01", approvedBy: "ferry", approvedAt: "2026-05-02", closedAt: "2026-05-31",
    closingNote: "Omset 72jt dari target 85jt. Stock loss naik sedikit, perlu kontrol inventaris." },
  { id: "sub-009", templateId: "tpl-outlet-retail", subUnitId: "rtl-outlet2", unitId: "retail", status: "closed", period: "Mei 2026",
    estimatedValues: { f1: 55000000, f2: 0, f3: 900, f4: 1200000 },
    actualValues:    { f1: 44000000, f2: 0, f3: 820, f4: 2100000 },
    fieldWeights: { f1: 30, f3: 20, f4: 20, f5: 30 }, subUnitWeight: 40,
    createdBy: "ferry", createdAt: "2026-05-01", approvedBy: "budhi", approvedAt: "2026-05-03", closedAt: "2026-05-31",
    closingNote: "Omset 44jt di bawah target 55jt. Outlet belum punya PIC tetap — input oleh Leader. Stock loss tinggi perlu perhatian." },
  { id: "sub-010", templateId: "tpl-cabang-pulsa", subUnitId: "xpc-main", unitId: "xpanca", status: "closed", period: "Mei 2026",
    estimatedValues: { f1: 12000, f2: 120000000, f3: 9000000, f4: 200, f5: 170 },
    actualValues:    { f1: 13500, f2: 138000000, f3: 9500000, f4: 205, f5: 188 },
    fieldWeights: { f1: 25, f2: 25, f6: 20, f7: 10, f8: 20 }, subUnitWeight: 100,
    createdBy: "fahrizal", createdAt: "2026-05-01", approvedBy: "budhi", approvedAt: "2026-05-02", closedAt: "2026-05-31",
    closingNote: "Margin 138jt melampaui target 120jt. Performa sangat baik, distribusi tumbuh pesat." },
  { id: "sub-011", templateId: "tpl-kolam-pembesaran", subUnitId: "aqua-ciwastra", unitId: "aquaculture", status: "approved", period: "Siklus Apr-Jul 2026",
    estimatedValues: { f3: 15000, f4: 85, f5: 200, f6: 1.2, f7: 24000, f8: 180 },
    actualValues: null, fieldWeights: { f4: 25, f6: 25, f21: 25, f25: 25 }, subUnitWeight: 30,
    createdBy: "satya", createdAt: "2026-04-10", approvedBy: "budhi", approvedAt: "2026-04-12", closedAt: null, closingNote: null },
];

export const AUDIT_LOG = [
  { ts: "2026-05-31T16:45:00", actorId: "andi",     action: "close",   entityType: "kpi_submission", entityId: "sub-004", entityLabel: "Closing KPI Pixel BDG Pusat",            unitId: "pixel",       details: "Pertumbuhan transaksi naik 8% dari bulan lalu, didorong promo Lebaran.", diff: null },
  { ts: "2026-05-31T15:20:00", actorId: "budhi",    action: "approve", entityType: "kpi_submission", entityId: "sub-004", entityLabel: "Approve closing Pixel BDG Pusat Mei",    unitId: "pixel",       details: null, diff: null },
  { ts: "2026-05-28T14:30:00", actorId: "rafli",    action: "close",   entityType: "kpi_submission", entityId: "sub-001", entityLabel: "Closing KPI Cerelek Siklus Feb-Mei",     unitId: "aquaculture", details: "Panen H+105. SR sedikit di bawah target karena suhu malam turun.", diff: null },
  { ts: "2026-05-28T15:00:00", actorId: "budhi",    action: "approve", entityType: "kpi_submission", entityId: "sub-001", entityLabel: "Approve closing Cerelek Siklus Feb-Mei", unitId: "aquaculture", details: null, diff: null },
  { ts: "2026-05-22T10:15:00", actorId: "wahyu",    action: "close",   entityType: "kpi_submission", entityId: "sub-003", entityLabel: "Closing KPI Cisampih Siklus Feb-Mei",    unitId: "aquaculture", details: null, diff: null },
  { ts: "2026-05-20T09:30:00", actorId: "wahyu",    action: "create",  entityType: "kpi_submission", entityId: "sub-003", entityLabel: "Ajukan KPI Cisampih Siklus Mei-Agu",     unitId: "aquaculture", details: "Estimasi tebar 11.000 ekor, target SR 85%", diff: null },
  { ts: "2026-05-17T11:20:00", actorId: "budhi",    action: "approve", entityType: "kpi_submission", entityId: "sub-002", entityLabel: "Approve estimasi Cerelek Siklus Mei-Agu", unitId: "aquaculture", details: "Bobot SR dinaikkan dari 20% ke 25%", diff: null },
  { ts: "2026-05-17T11:18:00", actorId: "budhi",    action: "update",  entityType: "weight",         entityId: "sub-002", entityLabel: "Update bobot KPI Cerelek Mei-Agu",       unitId: "aquaculture", details: null, diff: { before: "SR: 20%, FCR: 25%", after: "SR: 25%, FCR: 25%" } },
  { ts: "2026-05-15T14:00:00", actorId: "rafli",    action: "create",  entityType: "kpi_submission", entityId: "sub-002", entityLabel: "Ajukan KPI Cerelek Siklus Mei-Agu",      unitId: "aquaculture", details: null, diff: null },
  { ts: "2026-05-10T09:00:00", actorId: "budhi",    action: "create",  entityType: "sub_unit",       entityId: "rtl-outlet2", entityLabel: "Tambah Sub Unit: Outlet Setiabudi",  unitId: "retail",      details: null, diff: null },
  { ts: "2026-05-08T16:30:00", actorId: "budhi",    action: "update",  entityType: "user",           entityId: "bayu",    entityLabel: "Assign Bayu sebagai PIC Outlet Dago",    unitId: "retail",      details: null, diff: null },
  { ts: "2026-05-05T10:00:00", actorId: "sugianto", action: "create",  entityType: "project",        entityId: "pj-202",  entityLabel: "Ajukan Project: Upgrade Sistem POS",     unitId: "pixel",       details: "Estimasi budget Rp 28Jt, target selesai Jun 2026", diff: null },
  { ts: "2026-05-05T11:30:00", actorId: "budhi",    action: "approve", entityType: "project",        entityId: "pj-202",  entityLabel: "Approve project: Upgrade Sistem POS",    unitId: "pixel",       details: null, diff: null },
  { ts: "2026-05-02T13:45:00", actorId: "budhi",    action: "approve", entityType: "kpi_submission", entityId: "sub-004", entityLabel: "Approve estimasi Pixel BDG Pusat Mei",   unitId: "pixel",       details: null, diff: null },
  { ts: "2026-05-01T09:00:00", actorId: "andi",     action: "create",  entityType: "kpi_submission", entityId: "sub-004", entityLabel: "Ajukan KPI Pixel BDG Pusat Mei",         unitId: "pixel",       details: null, diff: null },
  { ts: "2026-04-30T17:00:00", actorId: "hendra",   action: "close",   entityType: "kpi_submission", entityId: "sub-h01", entityLabel: "Closing KPI Tanjung Blok A April",       unitId: "tanjung",     details: null, diff: null },
  { ts: "2026-04-15T10:20:00", actorId: "budhi",    action: "create",  entityType: "form_template",  entityId: "tpl-outlet-retail", entityLabel: "Buat template baru: Outlet Retail Bulanan", unitId: "retail", details: null, diff: null },
  { ts: "2026-04-10T14:00:00", actorId: "satya",    action: "create",  entityType: "project",        entityId: "pj-001",  entityLabel: "Ajukan Project: Pembukaan Kolam Cerelek 2", unitId: "aquaculture", details: null, diff: null },
];
